# -*- coding: utf-8 -*-
"""[4-1] 11th_모의대회.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEvxHUcYSRc66huINaVfOIQGKfBQ0Oji
"""

!pip install kaggle

import os
import zipfile
import numpy as np

# Kaggle API 설정
os.environ['KAGGLE_USERNAME'] = 'pkticc'
os.environ['KAGGLE_KEY'] = '713b09172665cec271e5d14ef99e9775'

# 대회 데이터 다운로드
!kaggle competitions download -c cupmachinelearning2024

# 압축 해제
with zipfile.ZipFile("/content/cupmachinelearning2024.zip","r") as zip_ref:
    zip_ref.extractall("/content/wine_data")

# 데이터 로드
train_df = pd.read_csv("/content/wine_data/train.csv")
test_df = pd.read_csv("/content/wine_data/test.csv")
submission_df = pd.read_csv("/content/wine_data/sample_submission.csv")

# 데이터 확인
train_df.info()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

train_df.rename(columns={'Unnamed: 0': 'ID'}, inplace=True)
X = train_df[['ID','alcohol', 'sugar', 'pH']]
y = train_df['class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train.astype(str))

# 트리 시각화
plt.figure(figsize=(20,10))
plot_tree(clf, feature_names=['ID', 'alcohol', 'sugar', 'pH'], class_names=clf.classes_, filled=True, rounded=True)
plt.show()

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test.astype(str), y_pred)
print(f"Model accuracy: {accuracy * 100:.2f}%")

test_df.rename(columns={'Unnamed: 0': 'ID'}, inplace=True)
X_pred = test_df[['ID', 'alcohol', 'sugar', 'pH']]
submission_df['class'] = clf.predict(X_pred)

submission_df.to_csv('/content/submission.csv', index=False)

!kaggle competitions submit -c cupmachinelearning2024 -f submission.csv -m "My first submission"

